### ISSUE TITLE
Price for DIGIFINEX totally wrong!

### ISSUE THREAD

**Issue by zydjohnHotmail** [coinapi/coinapi-sdk#154]
Hello:
I have been using the SDK for a few months, mostly the SDK works well.
However, I found that one exchange has the totally wrong data, it is: DIGIFINEX 
For the following HTTP current quote request:
https://rest.coinapi.io/v1/quotes/current?filter_symbol_id=DIGIFINEX_SPOT_BTC_USDT
The returned Json data is like this:
[
	{
		"symbol_id": "DIGIFINEX_SPOT_BTC_USDT_566C5A",
		"time_exchange": "2023-03-05T21:20:01.9989758Z",
		"time_coinapi": "2023-03-05T21:20:01.9962680Z",
		"ask_price": 0.000530000000000000014,
		"ask_size": 22481.02,
		"bid_price": 121.83132,
		"bid_size": 22350.12,
		"last_trade": {
			"time_exchange": "2023-03-05T21:20:01.0000000Z",
			"time_coinapi": "2023-03-05T21:20:02.3345829Z",
			"uuid": "1d3ec930-d104-4c65-b420-581231ab7b5b",
			"price": 22479.68,
			"size": 0.04135,
			"taker_side": "BUY"
		}
	}
]
The bid_price and bid_size, the ask_price and ask_size totally screwed.
Please fix the issue ASAP.
Thanks,

**Comment by MaxZaw** [comment]
Hello @zydjohnHotmail ,

Thank you for bringing this to our attention and for your continued use of our SDK.

We have reviewed the issue you reported regarding the DIGIFINEX exchange data. Upon checking, it appears that the endpoint you mentioned is currently providing accurate data. It is possible that the issue was a temporary glitch or has been resolved in the meantime.

We appreciate your vigilance in helping us maintain the accuracy and reliability of our data. If you encounter any further discrepancies or have any other concerns, please do not hesitate to reach out. We are here to assist you.

Thank you for your cooperation and understanding.

**Comment by zydjohnHotmail** [comment]
Hi,
Thanks for your reply, but I gave up to use it any more.
